export {
    productApi,
    productService,
    getByCategory,
    getAll,
    getAdmin,
    getById,
    getByIdAdmin,
    create,
    update,
    deleteProduct,
    updateStatus,
    addImages,
    getImages,
    deleteImage,
    setMainImage,
    type UpdateProductPayload,
} from './productApi';
