spring.application.name=ecommerce

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# Perfil activo por defecto
spring.profiles.active=dev

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Ordena los endpoints por
# metodo HTTP (GET, POST, PATCH, DELETE)
springdoc.swagger-ui.operations-sorter=method

# Agrupa por tags
springdoc.swagger-ui.tags-sorter=alpha

# Swagger UI disponible en: http://localhost:8080/swagger-ui.html

# Storage
api.storage.provider=local
api.storage.local.path=uploads/comprobantes
api.storage.allowed-types=image/png,image/jpeg,application/pdf
api.storage.max-size-mb=5

# Cloudinary (completar cuando tengas la cuenta)
# api.storage.cloudinary.cloud-name=tu_cloud_name
# api.storage.cloudinary.api-key=tu_api_key
# api.storage.cloudinary.api-secret=tu_api_secret