# Base de datos local
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce-ea
spring.datasource.username=postgres
spring.datasource.password=xlaboratory0204

# JWT
api.security.secret=123456789
api.security.expiration=120

# spring.jpa.show-sql=false