# Base de datos local
spring.datasource.url=jdbc:postgresql://host-produccion:5432/ecommerce_prod
spring.datasource.username=usuario_prod
spring.datasource.password=password_seguro_prod

# JWT - usar siempre un secreto largo y aleatorio en producción
api.security.secret=secreto_super_seguro_generado_con_oppenssl
api.security.expiration=3600

# En producción no mostrar SQL
spring.jpa.show-sql=false
